name: Lead Agent Workflow

on:
  schedule:
    - cron: '0 */3 * * *'  # alle 3 Stunden
  workflow_dispatch:

jobs:
  run-lead-agent:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run lead agent
        env:
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}
        run: |
          python lead_agent.py
