name: run-lead-agent

on:
  schedule:
    - cron: '0 */3 * * *'  # Alle 3 Stunden
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Repository klonen
        uses: actions/checkout@v3

      - name: Python einrichten
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Abhängigkeiten installieren
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lead-Agent ausführen
        run: |
          python -m lead_agent.main
