name: Lead Agent

on:
  workflow_dispatch:        # du kannst es manuell starten
  schedule:
    - cron: "0 */3 * * *"   # automatisch alle 3 Stunden

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Lead Agent
        env:
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          RECIPIENTS: ${{ secrets.RECIPIENTS }}
          SMTP_HOST: smtp.gmail.com
          SMTP_PORT: 587
          SEARCH_TERMS_JSON: '["FNQ-R","LP-CC","KTK","KTK-R","FNM-15","LPJ","AJT","ATDR","ATQR","TRM15"]'
        run: |
          python -m lead_agent.main
