name: Lead Agent

on:
  workflow_dispatch:            # manuell startbar
  schedule:
    - cron: "0 */3 * * *"       # alle 3 Stunden

concurrency:
  group: lead-agent
  cancel-in-progress: true      # keine überlappenden Läufe

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Lead Agent
        env:
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          RECIPIENTS: ${{ secrets.RECIPIENTS }}
          SMTP_HOST: smtp.gmail.com
          SMTP_PORT: 587
          # Keywords für website_scanner (kannst du anpassen)
          SEARCH_TERMS_JSON: '["FNQ-R","LP-CC","KTK","KTK-R","FNM-15","LPJ","AJT","ATDR","ATQR","TRM15"]'
        run: |
          python -m lead_agent.main

      - name: Upload CSV (Debug/Download)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: leads
          path: /tmp/leads.csv
          if-no-files-found: ignore
          retention-days: 7
