# === ai_lead_agent/main.py ===
from ted_scraper import check_ted
from bund_scraper import check_bund
from website_crawler import crawl_websites
from kleinanzeigen_checker import check_kleinanzeigen
from email_reporter import send_summary

if __name__ == "__main__":
    ted_results = check_ted()
    bund_results = check_bund()
    website_results = crawl_websites()
    kleinanzeigen_results = check_kleinanzeigen()

    all_leads = ted_results + bund_results + website_results + kleinanzeigen_results

    send_summary(all_leads)
